import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../components/Layout";
import Link from "next/link";
import Image from "next/image";
import { HiArrowNarrowRight } from "react-icons/hi";
import { motion } from "framer-motion";

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Aditya Arga | Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {/* content */}
      <motion.div
        initial={{ y: -100, opacity: 0 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
      >
        <div className="w-full bg-[#fbfcfd] backdrop-blur-sm pt-20">
          <div className="w-[50rem] h-[30rem] bg-glare-ef bg-no-repeat absolute top-0 right-0 -z-10"></div>
          <div className="w-full max-w-[900px] text-gray-500 mx-auto px-8">
            <div className="flex flex-col items-center md:flex-row-reverse md:justify-between">
              <div className="w-[200px]">
                <Image
                  src="/saya.jpeg"
                  alt=""
                  width="200px"
                  height="200px"
                  className="object-cover md:h-[150px] md:w-[150px] rounded-full"
                />
              </div>
              <div className="w-full">
                <h1 className="text-4xl font-bold mt-8">Aditya Argadinata</h1>
                <p className="text-xl text-transparent bg-clip-text font-semibold mt-4 bg-gradient-to-l from-[#0c17a8] to-[#4fd8e2]">
                  Student & Frontend Developer
                </p>
                <p className="mt-4">
                  hello, I am Aditya Argadinata, A person who love to code and
                  music. very intersted in web development, And now i am
                  learning a fullstack of Javascript environtment{" "}
                </p>
              </div>
            </div>

            {/* featured article */}
            <div className="mt-28">
              <p className="text-3xl font-bold">Featured Portfolio</p>
              <div className="w-full mt-4 border-2 border-[#0c8c96] p-4">
                <h4 className="text-lg font-semibold">Weeblog</h4>
                <p className="pt-2">
                  Blog starter with Next.js and Prisma, with a clean design.
                </p>
                <div className="flex items-center mt-2 gap-2">
                  <Image src="/react.png" alt="" width="20px" height="20px" />
                  <Image
                    src="/tailwind.png"
                    alt=""
                    width="20px"
                    height="20px"
                  />
                  <Image src="/vite.png" alt="" width="20px" height="20px" />
                  <Image
                    src="/prisma.png"
                    alt=""
                    width="35px"
                    height="35px"
                    className="-translate-x-2"
                  />
                </div>
              </div>
              <div className="w-full mt-4 border-2 border-[#0c8c96] p-4">
                <h4 className="text-lg font-semibold">Bugnime</h4>
                <p className="pt-2">The anime web downloader without ads</p>
                <div className="flex items-center mt-2 gap-2">
                  <Image src="/react.png" alt="" width="20px" height="20px" />
                  <Image
                    src="/tailwind.png"
                    alt=""
                    width="20px"
                    height="20px"
                  />
                  <Image src="/vite.png" alt="" width="20px" height="20px" />
                </div>
              </div>
              <Link href="/portfolio">
                <a className="flex items-center gap-2 mt-2">
                  <span>All Portofolios </span> <HiArrowNarrowRight />
                </a>
              </Link>
            </div>
          </div>
        </div>
      </motion.div>
    </Layout>
  );
};

export default Home;
